24w21b

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,7 +62,8 @@ jobs:
           tag: ${{ env.VERSION }}
           allowUpdates: true
         env:
-          export PATH: $PATH:/usr/local/go/bin     
+          export PATH: $PATH:/usr/local/go/bin
+
   docker:
     runs-on: ubuntu-latest
     needs: build  # 确保这个作业在 build 作业完成后运行
@@ -102,3 +103,45 @@ jobs:
           tags: | 
             ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
             ${{ env.IMAGE_NAME }}:latest
+
+  docker-nocache:
+    runs-on: ubuntu-latest 
+    needs: build  # 确保这个作业在 build 作业完成后运行
+    env:
+      IMAGE_NAME: wjqserver/ghproxy  # 定义镜像名称变量
+      DOCKERFILE: docker/dockerfile/nocache/Dockerfile  # 定义 Dockerfile 路径变量
+          
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Load VERSION
+        run: |
+          if [ -f VERSION ]; then
+            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+          else
+            echo "VERSION file not found!" && exit 1
+          fi
+      - name: Wait for Compile
+        run: sleep 300s
+          
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+          
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+          
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          
+      - name: 构建镜像
+        uses: docker/build-push-action@v6
+        with:
+          file: ./${{ env.DOCKERFILE }}
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: | 
+            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-nocache
+            ${{ env.IMAGE_NAME }}:nocache
